#include<iostream>
using namespace std;
void num19(int n1);
main()
{	int digit;
	cout<<"Enter a number (1-99): ";
	cin>> digit;
	num19(digit);
}
void num19(int n1)
{
	if(n1==1)
	cout<<"One";
	if(n1==2)
	cout<<"Two";
	if(n1==3)
	cout<<"Three";
	if(n1==4)
	cout<<"Four";
	if(n1==5)
	cout<<"Five";
	if(n1==6)
	cout<<"Six";
	if(n1==7)
	cout<<"Seven";
	if(n1==8)
	cout<<"Eight";
	if(n1==9)
	cout<<"Nine";
	if(n1==10)
	cout<<"Ten";
	if(n1==11)
	cout<<"Eleven";
	if(n1==12)
	cout<<"Twelve";
	if(n1==13)
	cout<<"Thirteen";
	if(n1==14)
	cout<<"Fourteen";
	if(n1==15)
	cout<<"Fifteen";
	if(n1==16)
	cout<<"Sixteen";
	if(n1==17)
	cout<<"Seventeen";
	if(n1==18)
	cout<<"Eighteen";
	if(n1==19)
	cout<<"Nineteen";
	if(n1==20)
	cout<<"Twenty";
	if(n1==21)
	cout<<"Twentyone";
	if(n1==22)
	cout<<"Twentytwo";
	if(n1==23)
	cout<<"Twentythree";
	if(n1==24)
	cout<<"Twentyfour";
	if(n1==25)
	cout<<"Twentyfive";
	if(n1==26)
	cout<<"Twentysix";
	if(n1==27)
	cout<<"Twentyseven";
	if(n1==28)
	cout<<"Twentyeight";
	 if(n1==29)
	cout<<"Twentynine";
	if(n1==30)
	cout<<"Thirty";
	if(n1==31)
	cout<<"Thirtyone";
	if(n1==32)
	cout<<"Thirtytwo";
	if(n1==33)
	cout<<"Thirtythree";
	if(n1==34)
	cout<<"Thirtyfour";
	if(n1==35)
	cout<<"Thirtyfive";
	if(n1==36)
	cout<<"Thirtysix";
	if(n1==37)
	cout<<"Thirtyseven";
	if(n1==38)
	cout<<"Thirtyeight";
	if(n1==39)
	cout<<"Thirtynine";
	if(n1==40)
	cout<<"Fourty";
	if(n1==41)
	cout<<"Fourtyone";
	if(n1==42)
	cout<<"Fourtytwo";
	if(n1==43)
	cout<<"Fourtythree";
	if(n1==44)
	cout<<"Fourtyfour";
	if(n1==45)
	cout<<"Fourtyfive";
	if(n1==46)
	cout<<"Fourtysix";
	if(n1==47)
	cout<<"Fourtyseven";
	if(n1==48)
	cout<<"Fourtyeight";
	if(n1==49)
	cout<<"Fourtynine";
	if(n1==50)
	cout<<"Fifty";
	if(n1==51)
	cout<<"Fiftyone";
	if(n1==52)
	cout<<"Fiftytwo";
	if(n1==53)
	cout<<"Fiftythree";
	if(n1==54)
	cout<<"Fiftyfour";
	if(n1==55)
	cout<<"Fiftyfive";
	if(n1==56)
	cout<<"Fiftysix";
	if(n1==57)
	cout<<"Fiftyseven";
	if(n1==58)
	cout<<"Fiftyeight";
	if(n1==59)
	cout<<"Fiftynine";
	if(n1==60)
	cout<<"Sixty";
	if(n1==61)
	cout<<"Sixtyone";
	if(n1==62)
	cout<<"Sixtytwo";
	if(n1==63)
	cout<<"Sixtythree";
	if(n1==64)
	cout<<"Sixtyfour";
	if(n1==65)
	cout<<"Sixtyfive";
	if(n1==66)
	cout<<"Sixtysix";
	if(n1==67)
	cout<<"Sixtyseven";
	if(n1==68)
	cout<<"Sixtyeight";
	if(n1==69)
	cout<<"Sixtynine";
	if(n1==70)
	cout<<"Seventy";
	if(n1==71)
	cout<<"Seventyone";
	if(n1==72)
	cout<<"Seventytwo";
	if(n1==73)
	cout<<"Seventythree";
	if(n1==74)
	cout<<"Seventyfour";
	if(n1==75)
	cout<<"Seventyfive";
	if(n1==76)
	cout<<"Seventysix";
	if(n1==77)
	cout<<"Seventyseven";
	if(n1==78)
	cout<<"Seventyeight";
	if(n1==79)
	cout<<"Seventynine";
	if(n1==80)
	cout<<"Eighty";
	if(n1==81)
	cout<<"Eightyone";
	if(n1==82)
	cout<<"Eightytwo";
	if(n1==83)
	cout<<"Eightythree";
	if(n1==84)
	cout<<"Eightyfour";
	if(n1==85)
	cout<<"Eightyfive";
	if(n1==86)
	cout<<"Eightysix";
	if(n1==87)
	cout<<"Eightyseven";
	if(n1==88)
	cout<<"Eightyeight";
	if(n1==89)
	cout<<"Eightynine";
	if(n1==90)
	cout<<"Ninty";
	if(n1==91)
	cout<<"Nintyone";
	if(n1==92)
	cout<<"Nintytwo";
	if(n1==93)
	cout<<"Nintythree";
	if(n1==94)
	cout<<"Nintyfour";
	if(n1==95)
	cout<<"Nintyfive";
	if(n1==96)
	cout<<"Nintysix";
	if(n1==97)
	cout<<"Nintyseven";
	if(n1==98)
	cout<<"Nintyeight";
	if(n1==99)
	cout<<"Nintynine";
	
}
